### ISSUE TITLE
provider name needs to be longer to avoid collision

### ISSUE THREAD

**Issue by nathantippy** [HarryEMartland/terraform-provider-appdynamics#24]
the provider name is appdynamics    so the resources and datasoruce names should start with appdynamics_ rather than appd_

When writing terraform seeing the full name appdynamics is much more descriptive and helpful to future maintainers than the appd_ prefix.

**Comment by HarryEMartland** [comment]
Yep good point, it has only recently been changed to appdynamcis.

**Comment by HarryEMartland** [comment]
Thanks for the issue! :D
