### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Vallher** [HarryEMartland/terraform-provider-appdynamics#36]
Hey,

I'm wondering about license of this provider. I have some plans to maybe use it, propably also fork and change some small things. I'm not sure that I'm allowed or not. Can I ask about adding a license file on the github level?:)

**Comment by HarryEMartland** [comment]
Hi Vallher, thanks for rasing this. I have added an MIT licence hope this is helpful to you?
Id be interested to see what you get up to with this. I tried to encourage AppD to work on config as code as their competitors support this e.g. New Relic. If we get enough users wanting this we may have more leverage.

Harry
